version: '3.8'

services:
  backend:
    build:
      context: ./backend
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    env_file: ./backend/.env
    depends_on:
      - mysqldb
    ports:
      - $PORT:$PORT
    expose:
      - '$PORT'
    volumes:
      - ./backend:/usr/app/backend
  mysqldb:
    image: mysql
    env_file: ./backend/.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
    ports:
      - '$MYSQL_PORT:$MYSQL_PORT'
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: