version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    command:
      - /bin/bash
      - -c
      - |
        ./wait-for-it.sh -t 120 $BACKEND_HOST:$BACKEND_PORT -- npm start
        npm start
    env_file: .env
    depends_on:
      - backend
    ports:
      - $FRONTEND_PORT:$FRONTEND_PORT
    expose:
      - '$FRONTEND_PORT'
    volumes:
      - ./frontend:/usr/app/frontend
      - /usr/app/frontend/node_modules
  backend:
    build:
      context: ./backend
    command:
      - /bin/bash
      - -c
      - |
        ./wait-for-it.sh -t 120 $MYSQL_HOST:$MYSQL_PORT -- npx sequelize-cli db:migrate
        npm start
    env_file: .env
    depends_on:
      - mysqldb
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    expose:
      - '$BACKEND_PORT'
    volumes:
      - ./backend:/usr/app/backend
      - /usr/app/backend/node_modules
  mysqldb:
    image: mysql
    env_file: .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '$MYSQL_PORT:$MYSQL_PORT'
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
  phpmyadmin:
    image: phpmyadmin
    env_file: .env
    environment:
      - PMA_HOST=$MYSQL_HOST
      - PMA_PORT=$MYSQL_PORT
    depends_on:
      - mysqldb
    ports:
      - 80:80

volumes:
  mysql:
  mysql_config: